/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;
import com.qlpg.dao.nguoiDungDAO;
import com.qlpg.entity.NguoiDung;
import com.qlpg.utils.Auth;
import com.qlpg.utils.MsgBox;
import com.qlpg.utils.ToanCuc;
import javax.swing.JOptionPane;
/**
 *
 * @author titob
 */
public class DangNhapJDialog extends javax.swing.JDialog {

    /**
     * Creates new form DangNhapJDialog
     */
    public DangNhapJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Đăng nhập hệ thống");
    }
    public boolean Validate() {
        if (txtMaNV.getText().isEmpty() || txtMatKhau.getPassword().equals("")) {
            MsgBox.alert(this, "Vui lòng nhập đầy đủ thông tin");
            return false;
        }
        return true;
    }
    public void DangNhap() {
        nguoiDungDAO dao = new nguoiDungDAO();
        String strMaNV = txtMaNV.getText();
        String strPass = new String(txtMatKhau.getPassword());
        NguoiDung nd = dao.selectById(strMaNV);
        if (nd == null) {
            MsgBox.alert(this, "Tài khoản không tồn tại");
        } else {
            if (!nd.getUserID().equals(strMaNV)) {
                MsgBox.alert(this, "Sai tên đăng nhập");
            } else if (!nd.getPassWord().equals(strPass)) {
                MsgBox.alert(this, "Sai mật khẩu đăng nhập");
            } else {
                if (nd.getVaiTro().equals("Quản lý")) {
                    JOptionPane.showMessageDialog(this, "Đăng nhập thành công - Quản lý");
                    ToanCuc tt = new ToanCuc();
                    tt.setTen(strMaNV);
                    tt.setVaitro(nd.getVaiTro());
                    tt.setMa(nd.getUserID());
                    this.dispose();
                } else if (nd.getVaiTro().equalsIgnoreCase("Học viên")) {
                    JOptionPane.showMessageDialog(this, "Đăng nhập thành công - Học viên");
                    // Mở form Học viên
                    ToanCuc tt = new ToanCuc();
                    tt.setTen(strMaNV);
                    tt.setVaitro(nd.getVaiTro());
                    tt.setMa(nd.getUserID());
                    this.dispose();
                } else if (nd.getVaiTro().equalsIgnoreCase("Nhân viên Sale")) {
                    JOptionPane.showMessageDialog(this, "Đăng nhập thành công - Nhân viên sale");
                    ToanCuc tt = new ToanCuc();
                    tt.setTen(strMaNV);
                    tt.setVaitro(nd.getVaiTro());
                    tt.setMa(nd.getUserID());
                    this.dispose();
                } else if (nd.getVaiTro().equalsIgnoreCase("Huấn luyện viên")) {
                    JOptionPane.showMessageDialog(this, "Đăng nhập thành công -  Huấn Luyện Viên ");
                    ToanCuc tt = new ToanCuc();
                    tt.setTen(strMaNV);
                    tt.setVaitro(nd.getVaiTro());
                    tt.setMa(nd.getUserID());
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Đăng nhập không thành công. Mã người dùng không hợp lệ.");
                }

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbldangNhap = new javax.swing.JLabel();
        lblMaMV = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        lblMatKhau = new javax.swing.JLabel();
        radHienMatKhau = new javax.swing.JCheckBox();
        btnKetThuc = new javax.swing.JButton();
        btnDangNhap = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ĐĂNG NHẬP");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 30, 200, 40);

        lbldangNhap.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbldangNhap.setForeground(new java.awt.Color(255, 255, 255));
        lbldangNhap.setText("Mời đăng nhập");
        jPanel1.add(lbldangNhap);
        lbldangNhap.setBounds(390, 80, 130, 21);

        lblMaMV.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMaMV.setForeground(new java.awt.Color(255, 255, 255));
        lblMaMV.setText("Tên đăng nhập:");
        jPanel1.add(lblMaMV);
        lblMaMV.setBounds(220, 140, 130, 21);

        txtMaNV.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtMaNV.setText("User004");
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaNV);
        txtMaNV.setBounds(350, 140, 230, 27);

        txtMatKhau.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtMatKhau.setText("pass321");
        jPanel1.add(txtMatKhau);
        txtMatKhau.setBounds(350, 200, 230, 27);

        lblMatKhau.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblMatKhau.setText("Mật khẩu:");
        jPanel1.add(lblMatKhau);
        lblMatKhau.setBounds(260, 200, 90, 21);

        radHienMatKhau.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        radHienMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        radHienMatKhau.setText("Hiện mật khẩu");
        radHienMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHienMatKhauActionPerformed(evt);
            }
        });
        jPanel1.add(radHienMatKhau);
        radHienMatKhau.setBounds(350, 240, 150, 25);

        btnKetThuc.setBackground(new java.awt.Color(0, 204, 255));
        btnKetThuc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PG/Icon/Stop24.png"))); // NOI18N
        btnKetThuc.setText("THOÁT");
        btnKetThuc.setMaximumSize(new java.awt.Dimension(155, 33));
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });
        jPanel1.add(btnKetThuc);
        btnKetThuc.setBounds(225, 290, 160, 40);

        btnDangNhap.setBackground(new java.awt.Color(0, 204, 255));
        btnDangNhap.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PG/Icon/dn.png"))); // NOI18N
        btnDangNhap.setText("ĐĂNG NHẬP");
        btnDangNhap.setPreferredSize(new java.awt.Dimension(155, 33));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangNhap);
        btnDangNhap.setBounds(400, 290, 180, 40);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PG/Icon/logoFT.png"))); // NOI18N
        jPanel1.add(lblLogo);
        lblLogo.setBounds(30, 70, 230, 230);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PG/Icon/backgroundDN.jpg"))); // NOI18N
        lblBackground.setMaximumSize(new java.awt.Dimension(5000, 2800));
        lblBackground.setPreferredSize(new java.awt.Dimension(600, 280));
        jPanel1.add(lblBackground);
        lblBackground.setBounds(0, 0, 610, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radHienMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHienMatKhauActionPerformed
        if (radHienMatKhau.isSelected()) {
            txtMatKhau.setEchoChar((char) 0); //password = JPasswordField
        } else {
            txtMatKhau.setEchoChar('*');
        }
    }//GEN-LAST:event_radHienMatKhauActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        if (MsgBox.confirm(this, "Bạn có chắn muốn thoát không")) {
            System.exit(0);
        };
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed

        if(Validate())
       {
           DangNhap(); 
       }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhapJDialog dialog = new DangNhapJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMaMV;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lbldangNhap;
    private javax.swing.JCheckBox radHienMatKhau;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtMatKhau;
    // End of variables declaration//GEN-END:variables
}
